apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: postgresql
  name: postgresql
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: postgresql
      version: '15.5.*'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  releaseName: postgresql
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    auth:
      postgresPassword: postgres_password
      username: temporal
      password: temporal_password
      database: temporal
    primary:
      service:
        type: NodePort
        nodePorts:
          postgresql: 30000
