apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      automountServiceAccountToken: false
      containers:
        - name: temporal-worker
          image: temporal-app:0.0.1
          command: ["npm", "start"]
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
            requests:
              cpu: 200m
              memory: "256Mi"
          env:
            - name: TEMPORAL_HOST_URL
              value: temporal-frontend.temporal.svc.cluster.local:7233
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: temporal-worker
spec:
  scaleTargetRef:
    name: temporal-worker
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 30    # Optional. Default: 300 seconds
  maxReplicaCount: 10   # Optional. Default: 100
  triggers:
  - type: postgresql
    metadata:
      host: "postgresql.postgresql.svc.cluster.local"
      userName: "temporal"
      dbname: "temporal"
      password: temporal_password
      query: "SELECT COUNT() FROM task_queue WHERE queue_name = 'slow'"
      targetQueryValue: "5"